import Foundation

public enum Mock {

    public static func factAboutNumber(_ number: Int) -> String {
        mockNumberFacts[number] ?? mockNumberFacts.randomElement()!.value
    }

    public static var cultureMindNames: [String] {
        mockCultureMindNames
    }

}

// MARK: - Number Facts

// Generated by ChatGPT
let mockNumberFacts: [Int: String] = [
    0: "Zero is the number of times a cat admits it's wrong.",
    1: "One is the number of ghosts afraid of their own shadows.",
    2: "Two is the number of socks a dog has hidden in a secret lair.",
    3: "Three is the number of aliens who secretly enjoy human sitcoms.",
    4: "Four is the number of times a snail considers racing a hare each day.",
    5: "Five is the number of times a penguin has thought about flying.",
    6: "Six is the number of seagulls needed to start a rock band.",
    7: "Seven is the number of times a goldfish remembers it's in a fishbowl.",
    8: "Eight is the number of languages spoken by educated earthworms.",
    9: "Nine is the number of out of ten kangaroos who prefer hopping to walking.",
    10: "Ten is the number of aliens who believe humans exist."
]

// MARK: - Culture Mind Names

// Generated by ChatGPT
let mockCultureMindNames: [String] = [
    "GSV Gravitas Of Misperception",
    "LSV Antithesis of Inefficiency",
    "ROU Paradox Unraveler",
    "VFP Occasional Determinist",
    "Superlifter Final Refutation of Solitude",
    "dROU Dialectic Resolution",
    "SV Limitless Tangents of Enquiry",
    "GCU Quantum Whisper",
    "GOU Apologia For Complexity",
    "GSV Cogito Ergo Sum Ad Infinitum",
    "LSV Oscillation Overthruster",
    "ROU Mirthful Contrarian",
    "VFP Solitaire Theorist",
    "Superlifter Quizzical Transgressor",
    "dROU Algorithm of Subtlety",
    "SV Emancipation from Orthodoxy",
    "GCU Counterfactual Supposition",
    "GOU Panegyric of Uncertainty",
    "GSV Axiom of Aleatory Phenomena",
    "LSV Serendipitous Eccentricity",
    "ROU Disquieting Omen of Foreknowledge",
    "VFP Parabolic Reverie",
    "Superlifter Gratuitous Complexity",
    "dROU Recursive Enigma",
    "SV Irrefutable Argument Against Silence",
    "GCU Persistence of Ambiguity",
    "GOU Uncertainty's Cheshire Smile",
    "GSV Unbounded Repository of Detachment",
    "LSV Elegant Disproof of Stasis",
    "ROU Tangled Webs We Weave"
]
